services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - 80:80
    environment:
      - BACKEND_SECRET_FILE=/run/secrets/backend-secret
    volumes:
      - type: bind
        source: ./src
        target: /code/app
    networks:
      - app-network
    secrets:
      - backend_secret
      - postgres_user
      - postgres_password
    depends_on:
      - postgres
      - redis


  postgres:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    expose:
      - "5432"
    secrets:
      - postgres_password
      - postgres_user
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_DB=news_db
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7.0.8-alpine
    ports:
      - 6379:6379
    expose:
      - "6379"
    volumes:
      - redis-data:/var/lib/redis/data
    networks:
      - app-network

volumes:
  pg-data:
  redis-data:

secrets:
  backend_secret:
    file: ./docker_secrets/backend_secret.txt
  postgres_password:
    file: ./docker_secrets/postgres_password.txt
  postgres_user:
    file: ./docker_secrets/postgres_user.txt

networks:
  app-network: {}
